            {[
              {
                id: 'mercedes-s-class',
                name: 'Mercedes-Benz S-Class S350d',
                modelYear: '2024–2025 S350d Executive',
                category: 'Ultra Luxury VIP Sedan',
                categoryKey: 'luxury',
                image: '/images/fleet/mercedes_s_class_chauffeur.jpg',
                gallery: [
                  '/images/fleet/mercedes_s_class_chauffeur.jpg',
                  '/images/fleet/mercedes_s_class_front.jpg',
                  '/images/fleet/mercedes_s_class_rear.jpg',
                  '/images/fleet/mercedes_s_class_interior.jpg'
                ],
                rating: 5.0,
                price: '15,000',
                period: '8h / 80km',
                passengerCapacity: 4,
                seatCategory: '3-4',
                luggageCapacity: 4,
                transmission: '9G-TRONIC Auto',
                fuelType: 'Diesel Turbo',
                ac: '4-Zone Climate',
                badgeText: 'KA 05 AG 4488',
                regPlate: 'KA 05 AG 4488',
                description: "Bangalore's flagship Mercedes-Benz S350d (KA 05 AG 4488) in pristine white finish. Featuring rear executive reclining seats, massage functions, dual rear entertainment screens, ambient cabin lighting, and English-speaking uniformed chauffeurs.",
                tariffs: {
                  halfDay: 'N/A (Full Day Only)',
                  fullDay: '₹15,000 (8h / 80km)',
                  extraHrKm: '₹1,500/hr • ₹150/km',
                  airportFlat: '₹20,000 (Airport VIP)',
                  outstationRate: '₹150/km (Min 300km/day)'
                },
                amenities: ['Rear Reclining Seats & Massage', 'Dual Entertainment Screens', 'Ambient Cabin Glow', 'English-Speaking Uniformed Chauffeur', 'Bottled Water & Wi-Fi', 'VIP Airport Protocol Escort']
              },
              {
                id: 'bmw-7-series',
                name: 'BMW 730Ld xDrive',
                modelYear: '2024–2025 Long Wheelbase Luxury',
                category: 'Ultra VIP Flagship Sedan',
                categoryKey: 'luxury',
                image: '/images/fleet/bmw_730ld_front.png',
                gallery: [
                  '/images/fleet/bmw_730ld_front.png',
                  '/images/fleet/bmw_730ld_front_quarter.png',
                  '/images/fleet/bmw_730ld_interior_front.png',
                  '/images/fleet/bmw_730ld_interior_rear.png',
                  '/images/fleet/bmw_730ld_rear.png'
                ],
                rating: 5.0,
                price: '15,000',
                period: '8h / 80km',
                passengerCapacity: 4,
                seatCategory: '3-4',
                luggageCapacity: 3,
                transmission: '8-Speed Steptronic',
                fuelType: 'Diesel Twin-Turbo (3.0L)',
                ac: '4-Zone Climate',
                badgeText: 'KA 51 AH 8780',
                regPlate: 'KA 51 AH 8780',
                description: "Siddhu Car Rentals' flagship BMW 730Ld xDrive (KA 51 AH 8780) in Mineral White Metallic. Features extended wheelbase rear executive lounge with cognac Nappa leather, diamond-quilted seats, dual rear entertainment screens, and rear climate console.",
                tariffs: {
                  halfDay: 'N/A (Full Day Only)',
                  fullDay: '₹15,000 (8h / 80km)',
                  extraHrKm: '₹1,500/hr • ₹150/km',
                  airportFlat: '₹20,000 (Airport VIP)',
                  outstationRate: '₹150/km (Min 300km/day)'
                },
                amenities: ['Cognac Nappa Leather Executive Lounge', 'Dual Rear Entertainment Screens', 'Diamond-Quilted Seats', '4-Zone Climate Control', 'Rear Center Console Controls', 'Uniformed English-Speaking Chauffeur']
              },
              {
                id: 'toyota-vellfire',
                name: 'Toyota Vellfire Executive Lounge',
                modelYear: '2024–2025 Executive Lounge Edition',
                category: 'Supreme VIP Luxury MPV',
                categoryKey: 'mpv',
                image: '/images/fleet/vellfire_front.png',
                gallery: [
                  '/images/fleet/vellfire_front.png',
                  '/images/fleet/vellfire_front_quarter.png',
                  '/images/fleet/vellfire_interior_front.png',
                  '/images/fleet/vellfire_interior_rear.png',
                  '/images/fleet/vellfire_rear.png'
                ],
                rating: 5.0,
                price: '22,500',
                period: '8h / 80km',
                passengerCapacity: 6,
                seatCategory: '5-7',
                luggageCapacity: 4,
                transmission: 'CVT Hybrid / Auto',
                fuelType: 'Hybrid Petrol (2.5L)',
                ac: 'Tri-Zone Climate',
                badgeText: 'KA 05 AR 7547',
                regPlate: 'KA 05 AR 7547',
                description: "Siddhu Car Rentals' crown jewel — the Toyota Vellfire Executive Lounge (KA 05 AR 7547) in Platinum White Pearl. Features ultra-premium cognac Nappa leather executive captain chairs with powered ottoman recliners, rear center console, and whisper-quiet hybrid drive.",
                tariffs: {
                  halfDay: 'N/A (Full Day Only)',
                  fullDay: '₹22,500 (8h / 80km)',
                  extraHrKm: '₹2,250/hr • ₹250/km',
                  airportFlat: '₹20,000 (Airport VIP)',
                  outstationRate: '₹250/km (Min 300km/day)'
                },
                amenities: ['Cognac Nappa Leather Ottoman Recliners', 'Powered Sliding Doors', 'Rear Entertainment & Climate Console', 'Ambient Ceiling Lighting', 'Whisper-Quiet Hybrid Drive', 'Uniformed English-Speaking Chauffeur']
              },
              {
                id: 'mercedes-e-class',
                name: 'Mercedes-Benz E-Class',
                modelYear: '2024–2025 E-Class Luxury',
                category: 'Luxury Executive Sedan',
                categoryKey: 'luxury',
                image: '/images/fleet/mercedes_e_class_front.jpg',
                gallery: [
                  '/images/fleet/mercedes_e_class_front.jpg',
                  '/images/fleet/mercedes_e_class_cockpit.png',
                  '/images/fleet/mercedes_e_class_rear_cabin.png',
                  '/images/fleet/mercedes_e_class_front_cabin.png',
                  '/images/fleet/mercedes_e_class_wedding.jpg'
                ],
                rating: 4.9,
                price: '10,000',
                period: '4h / 40km',
                passengerCapacity: 4,
                seatCategory: '3-4',
                luggageCapacity: 3,
                transmission: '9G-TRONIC Auto',
                fuelType: 'Diesel / Petrol Turbo',
                ac: 'Tri-Zone Climate',
                badgeText: 'KA 05 AN 5373',
                regPlate: 'KA 05 AN 5373',
                description: "Bangalore's premier Mercedes-Benz E-Class (KA 05 AN 5373) in pristine white finish. Featuring luxury beige leather seating, ambient cockpit illumination, dual-zone climate control, and experienced English-speaking uniformed chauffeurs.",
                tariffs: {
                  halfDay: '₹10,000 (4h / 40km)',
                  fullDay: '₹12,000 (8h / 80km)',
                  extraHrKm: '₹1,200/hr • ₹120/km',
                  airportFlat: '₹10,000 (Airport VIP)',
                  outstationRate: '₹120/km (Min 300km/day)'
                },
                amenities: ['Beige Leather Upholstery', 'Ambient Mood Lighting', 'English-Speaking Uniformed Chauffeur', 'Bottled Mineral Water', 'High-Speed Wi-Fi', 'Flight Arrival Escort']
              },
              {
                id: 'audi-q7',
                name: 'Audi Q7 Quattro Luxury SUV',
                modelYear: '2024–2025 Executive Edition',
                category: 'Executive Luxury SUV',
                categoryKey: 'suv',
                image: '/images/fleet/audi_q7.jpg',
                gallery: [
                  '/images/fleet/audi_q7.jpg',
                  '/images/fleet/audi_q7_interior.png',
                  '/images/fleet/audi_q7_cockpit.png',
                  '/images/fleet/audi_q7_rear_seats.png'
                ],
                rating: 4.9,
                price: '14,000',
                period: '8h / 80km',
                passengerCapacity: 6,
                seatCategory: '5-7',
                luggageCapacity: 4,
                transmission: 'Quattro Auto',
                fuelType: 'Diesel Turbo',
                ac: '4-Zone Deluxe AC',
                badgeText: 'KA Commercial VIP',
                regPlate: 'KA Commercial VIP',
                description: "Bangalore's premier luxury 7-seater SUV with plush beige leather interior, captain seating, panoramic glass roof, and Quattro all-wheel drive. Perfect for VIP family tours and corporate airport transit.",
                tariffs: {
                  halfDay: 'N/A (Full Day Only)',
                  fullDay: '₹14,000 (8h / 80km)',
                  extraHrKm: '₹1,400/hr • ₹140/km',
                  airportFlat: '₹15,000 (Airport VIP)',
                  outstationRate: '₹140/km (Min 300km/day)'
                },
                amenities: ['Beige Leather Interior', 'Panoramic Glass Sunroof', 'Rear Executive Armrests', 'Quattro AWD', 'Uniformed Chauffeur', 'Dual USB Fast Charging']
              },
              {
                id: 'honda-accord',
                name: 'Honda Accord Executive',
                modelYear: '2024–2025 Executive Luxury Edition',
                category: 'Executive Luxury Sedan',
                categoryKey: 'luxury',
                image: '/images/fleet/honda_accord_front.jpg',
                gallery: [
                  '/images/fleet/honda_accord_front.jpg',
                  '/images/fleet/honda_accord_interior_front.jpg',
                  '/images/fleet/honda_accord_interior_rear.jpg'
                ],
                rating: 4.9,
                price: '3,500',
                period: '4h / 40km',
                passengerCapacity: 4,
                seatCategory: '3-4',
                luggageCapacity: 3,
                transmission: 'Auto / Manual i-VTEC',
                fuelType: 'Petrol i-VTEC',
                ac: 'Dual-Zone Climate',
                badgeText: 'KA 05 AC 4023',
                regPlate: 'KA 05 AC 4023',
                description: "Bangalore's distinguished executive sedan — the Honda Accord (KA 05 AC 4023) in pristine pearl white finish. Featuring luxurious beige leather seating, rich woodgrain center console and door trim, dedicated rear AC vents, and rear passenger executive armrest.",
                tariffs: {
                  halfDay: '₹3,500 (4h / 40km)',
                  fullDay: '₹6,000 (8h / 80km)',
                  extraHrKm: '₹600/hr • ₹60/km',
                  airportFlat: '₹5,000 (Airport Flat)',
                  outstationRate: '₹60/km (Min 300km/day)'
                },
                amenities: ['Plush Beige Leather Upholstery', 'Rear Executive Armrest & Cup Holders', 'Dual-Zone Climate Control', 'Woodgrain Luxury Trim', 'Verified Uniformed Chauffeur', 'Complimentary Packaged Water']
              },
              {
                id: 'innova-crysta',
                name: 'Toyota Innova Crysta VIP',
                modelYear: '2024–2025 Luxury Edition',
                category: 'Executive MPV',
                categoryKey: 'mpv',
                image: '/images/fleet/innova_crysta_bronze_front.jpg',
                gallery: [
                  '/images/fleet/innova_crysta_bronze_front.jpg',
                  '/images/fleet/innova_crysta_bronze_side.png',
                  '/images/fleet/innova_crysta_bronze_rear.png',
                  '/images/fleet/innova_crysta_bronze_profile.png',
                  '/images/innova_crysta_luxury.jpg'
                ],
                rating: 4.9,
                price: '1,900',
                period: '4h / 40km',
                passengerCapacity: 6,
                seatCategory: '5-7',
                luggageCapacity: 5,
                transmission: 'Manual / Automatic',
                fuelType: 'Diesel Turbo',
                ac: 'Dual Front & Rear AC',
                badgeText: 'KA 05 AT 1728',
                regPlate: 'KA 05 AT 1728',
                description: "Siddhu Car Rentals' flagship Toyota Innova Crysta (KA 05 AT 1728) in refined bronze metallic finish with chrome styling. Features executive captain reclining seats, dual front and rear climate control, spacious luggage boot, and verified uniformed chauffeurs.",
                tariffs: {
                  halfDay: '₹1,900 (4h / 40km)',
                  fullDay: '₹3,200 (8h / 80km)',
                  extraHrKm: '₹275/hr • ₹23/km',
                  airportFlat: '₹2,600 (Airport Flat)',
                  outstationRate: '₹23/km (Min 300km/day)'
                },
                amenities: ['Captain Reclining Seats', 'Dual Zone Front & Rear AC', 'Large Luggage Boot', 'KA Yellow Board', 'Uniformed Chauffeur', 'GPS Live Tracking']
              },
              {
                id: 'innova-hycross',
                name: 'Toyota Innova Hycross Hybrid',
                modelYear: '2024–2025 VX Hybrid Edition',
                category: 'Hybrid Luxury MPV',
                categoryKey: 'mpv',
                image: '/images/fleet/innova_hycross_front.png',
                gallery: [
                  '/images/fleet/innova_hycross_front.png',
                  '/images/fleet/innova_hycross_side.png',
                  '/images/fleet/innova_hycross_rear.png'
                ],
                rating: 5.0,
                price: '2,600',
                period: '4h / 40km',
                passengerCapacity: 6,
                seatCategory: '5-7',
                luggageCapacity: 5,
                transmission: 'e-CVT Automatic',
                fuelType: 'Strong Hybrid Petrol',
                ac: 'Multi-Zone Climate',
                badgeText: 'KA 05 AR 7546',
                regPlate: 'KA 05 AR 7546',
                description: "Siddhu Car Rentals' flagship Toyota Innova Hycross Hybrid (KA 05 AR 7546) in pristine pearl white finish. Features ultra-smooth electric hybrid drive, plush captain seating, multi-zone climate control, expansive legroom, and verified uniformed chauffeurs.",
                tariffs: {
                  halfDay: '₹2,600 (4h / 40km)',
                  fullDay: '₹4,100 (8h / 80km)',
                  extraHrKm: '₹250/hr • ₹24/km',
                  airportFlat: '₹2,500 (Airport Flat)',
                  outstationRate: '₹24/km (Min 300km/day)'
                },
                amenities: ['Ultra-Quiet Electric Hybrid Drive', 'Captain Reclining Seats', 'Multi-Zone Climate Control', 'Large Luggage Boot', 'KA Yellow Board VIP', 'Uniformed Chauffeur']
              },
              {
                id: 'toyota-commuter',
                name: 'Toyota HiAce Commuter VIP',
                modelYear: '2024–2025 Luxury Lounge Edition',
                category: 'VIP Luxury Lounge Van',
                categoryKey: 'coach',
                image: '/images/fleet/toyota_commuter.jpg',
                gallery: [
                  '/images/fleet/toyota_commuter.jpg',
                  '/images/fleet/toyota_commuter_side.jpg',
                  '/images/fleet/toyota_commuter_interior_tv.jpg',
                  '/images/fleet/toyota_commuter_cabin_lounge.jpg',
                  '/images/fleet/toyota_commuter_roof_lighting.jpg'
                ],
                rating: 5.0,
                price: '7,500',
                period: '4h / 40km',
                passengerCapacity: 9,
                seatCategory: '8-12',
                luggageCapacity: 8,
                transmission: 'Auto / Manual D-4D',
                fuelType: 'Diesel Turbo',
                ac: 'Roof High-Capacity AC',
                badgeText: 'KA 05 AP 9988',
                regPlate: 'KA 05 AP 9988',
                description: "Exclusive custom luxury Toyota HiAce Commuter VIP Lounge featuring diamond-stitched beige leather recliner captain seats, ceiling ambient LED mood lighting, large entertainment TV screen, surround audio console, and window privacy curtains.",
                tariffs: {
                  halfDay: '₹7,500 (4h / 40km)',
                  fullDay: '₹9,000 (8h / 80km)',
                  extraHrKm: '₹900/hr • ₹90/km',
                  airportFlat: '₹9,000 (Airport VIP)',
                  outstationRate: '₹90/km (Min 300km/day)'
                },
                amenities: ['Diamond Recliner Captain Seats', 'Large LED TV Entertainment & Audio', 'Ambient Blue LED Roof Lighting', 'Privacy Window Curtains', 'High Standing Roof', 'KA Yellow Board VIP']
              },
              {
                id: 'traveller',
                name: 'Force Traveller Luxury AC',
                modelYear: '2024–2025 Luxury High-Roof Edition',
                category: 'VIP Group Coach',
                categoryKey: 'coach',
                image: '/images/fleet/force_traveller_front.png',
                gallery: [
                  '/images/fleet/force_traveller_front.png',
                  '/images/fleet/force_traveller_interior_seats.jpg',
                  '/images/fleet/force_traveller_cabin_view.jpg',
                  '/images/fleet/force_traveller_roof_tv.jpg',
                  '/images/fleet/force_traveller_rear.png'
                ],
                rating: 4.9,
                price: '6,000',
                period: '8h / 80km',
                passengerCapacity: 16,
                seatCategory: '8-12',
                luggageCapacity: 10,
                transmission: 'Manual FM 2.6 CR',
                fuelType: 'Turbo Diesel',
                ac: 'Roof Multi-Vent High-Capacity AC',
                badgeText: 'KA 05 AP 1000',
                regPlate: 'KA 05 AP 1000',
                description: "Siddhu Car Rentals' flagship Force Traveller Luxury AC (KA 05 AP 1000) in pristine white finish with VIP high roof. Features 2x1 high-back push-back reclining seats in sporty dual-tone blue/black fabric, wide red carpeted aisle, high-fidelity surround audio speakers, front LED TV entertainment console with custom roof lighting, luggage racks, and emergency exit.",
                tariffs: {
                  halfDay: '₹4,500 (4h / 40km)',
                  fullDay: '₹6,000 (8h / 80km)',
                  extraHrKm: '₹500/hr • ₹25/km',
                  airportFlat: '₹5,000 (Airport Flat)',
                  outstationRate: '₹25/km (Min 300km/day)'
                },
                amenities: ['2x1 High-Back Recliner Seats', 'LED TV & Hi-Fi Audio Surround', 'Roof Multi-Vent High-Capacity AC', 'Curtained Privacy Windows', 'Rear Ladder & Luggage Carrier', 'Uniformed Highway Driver']
              }
            ]